/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lenovo' at '8/26/16 11:02 PM' with Gradle 3.0
 *
 * @author lenovo, @date 8/26/16 11:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
